apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpcds-data-gen
  labels:
    app.kubernetes.io/name: tpcds-data-gen
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app.kubernetes.io/name: tpcds-data-gen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tpcds-data-gen
    spec:
      serviceAccountName: byzer
      securityContext:
        {}
      containers:
        - name: tpcds-data-gen
          securityContext: {}
          image: "byzer/byzer-lang-k8s-aws:3.1.1-2.3.2-20220817"
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - cat << EOF | bash
              /work/spark-3.1.1-bin-hadoop3.2/bin/spark-submit --master k8s_api_server
              --deploy-mode cluster
              --class tech.mlsql.byzer.benchmark.tpcds.DataGeneration
              --conf spark.kubernetes.container.image=byzer/byzer-lang-k8s-aws:3.1.1-2.3.2-20220817
              --conf spark.driver.memory=4g
              --conf spark.driver.cores=1
              --conf spark.executor.memory=2g
              --conf spark.executor.cores=1
              --conf spark.executor.instances=8
              --conf spark.kubernetes.namespace=flag-qa
              --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem        
              local:///home/deploy/byzer-benchmark/libs/byzer-benchmark-0.0.1.jar
              s3a://zjc-2/tpcds_parquet_nojuicefs_1gb
              /opt/tpcds-kit/tools
              parquet
              1
              10
              false
              false
              false
              EOF
      restartPolicy: Always
